module.exports = {
    events: [
      {
        id: 1,
        name: "Mulheres que Mudam o Mundo com a Tecnologia",
        organization: "Developer Girls",
        date: "2024-03-16T00:00:00.000Z",
        location: "Campo Grande, MS",
        price: 100,
        rating: "10",
        image_url: "https://images.sympla.com.br/65c2f14eac7a9-lg.png"
      },
      {
        id: 2,
        name: "Mulheres que Mudam o Mundo com a Tecnologia",
        organization: "Developer Girls",
        date: "2024-03-15T00:00:00.000Z",
        location: "Campo Grande, MS",
        price: 10,
        rating: "14",
        image_url: "https://images.sympla.com.br/65c2f14eac7a9-lg.png"
      },
      {
        id: 3,
        name: "Mulheres que Mudam o Mundo com a Tecnologia",
        organization: "Developer Girls",
        date: "2024-03-14T00:00:00.000Z",
        location: "Campo Grande, MS",
        price: 160,
        rating: "16",
        image_url: "https://images.sympla.com.br/65c2f14eac7a9-lg.png"
      },
    ],
    spots: [
        {id: 1, name: "A1", status: 'available', event_id: 1},
        {id: 2, name: "A2", status: 'available', event_id: 1},
        {id: 3, name: "A3", status: 'available', event_id: 1},
        {id: 4, name: "A4", status: 'available', event_id: 1},
        {id: 5, name: "A5", status: 'available', event_id: 1},
        {id: 6, name: "B1", status: 'available', event_id: 1},
        {id: 7, name: "B2", status: 'available', event_id: 1},
        {id: 8, name: "B3", status: 'available', event_id: 1},
        {id: 9, name: "B4", status: 'available', event_id: 1},
        {id: 10, name: "B5", status: 'available', event_id: 1},

        {id: 1, name: "A1", status: 'available', event_id: 2},
        {id: 2, name: "A2", status: 'available', event_id: 2},
        {id: 3, name: "A3", status: 'available', event_id: 2},
        {id: 4, name: "A4", status: 'available', event_id: 2},
        {id: 5, name: "A5", status: 'available', event_id: 2},
        {id: 6, name: "A6", status: 'available', event_id: 2},
        {id: 7, name: "A7", status: 'available', event_id: 2},
        {id: 8, name: "A8", status: 'available', event_id: 2},
        {id: 9, name: "A9", status: 'available', event_id: 2},
        {id: 10, name: "A10", status: 'available', event_id: 2},
        {id: 11, name: "B1", status: 'available', event_id: 2},
        {id: 12, name: "B2", status: 'available', event_id: 2},
        {id: 13, name: "B3", status: 'available', event_id: 2},
        {id: 14, name: "B4", status: 'available', event_id: 2},
        {id: 15, name: "B5", status: 'available', event_id: 2},
        {id: 16, name: "B6", status: 'available', event_id: 2},
        {id: 17, name: "B7", status: 'available', event_id: 2},
        {id: 18, name: "B8", status: 'available', event_id: 2},
        {id: 19, name: "B9", status: 'available', event_id: 2},
        {id: 20, name: "B10", status: 'available', event_id: 2},

        {id: 1, name: "A1", status: 'available', event_id: 3},
        {id: 2, name: "A2", status: 'available', event_id: 3},
        {id: 3, name: "A3", status: 'available', event_id: 3},
        {id: 4, name: "A4", status: 'available', event_id: 3},
        {id: 5, name: "A5", status: 'available', event_id: 3},
        {id: 6, name: "A6", status: 'available', event_id: 3},
        {id: 7, name: "A7", status: 'available', event_id: 3},
        {id: 8, name: "A8", status: 'available', event_id: 3},
        {id: 9, name: "A9", status: 'available', event_id: 3},
        {id: 10, name: "A10", status: 'available', event_id: 3},
        {id: 11, name: "A11", status: 'available', event_id: 3},
        {id: 12, name: "A12", status: 'available', event_id: 3},
        {id: 13, name: "A13", status: 'available', event_id: 3},
        {id: 14, name: "A14", status: 'available', event_id: 3},
        {id: 15, name: "A15", status: 'available', event_id: 3},
        {id: 16, name: "B1", status: 'available', event_id: 3},
        {id: 17, name: "B2", status: 'available', event_id: 3},
        {id: 18, name: "B3", status: 'available', event_id: 3},
        {id: 19, name: "B4", status: 'available', event_id: 3},
        {id: 20, name: "B5", status: 'available', event_id: 3},
        {id: 21, name: "B6", status: 'available', event_id: 3},
        {id: 22, name: "B7", status: 'available', event_id: 3},
        {id: 23, name: "B8", status: 'available', event_id: 3},
        {id: 24, name: "B9", status: 'available', event_id: 3},
        {id: 25, name: "B10", status: 'available', event_id: 3},
        {id: 26, name: "B11", status: 'available', event_id: 3},
        {id: 27, name: "B12", status: 'available', event_id: 3},
        {id: 28, name: "B13", status: 'available', event_id: 3},
        {id: 29, name: "B14", status: 'available', event_id: 3},
        {id: 30, name: "B15", status: 'available', event_id: 3},
    ]
  };
